-- Script to create the reservation table for the library management system
-- Run this script in your Oracle database

-- Connect to your schema/database before running this script
-- No USE statement needed in Oracle

-- Drop table if exists (in case of previous failed attempts)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE reservation';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Create reservation table with matching column types (without foreign keys first)
CREATE TABLE reservation (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbnLivre VARCHAR2(20) NOT NULL,
    numeroAdherent VARCHAR2(50) NOT NULL,
    dateReservation DATE NOT NULL,
    statut VARCHAR2(20) DEFAULT 'en_attente' CHECK (statut IN ('en_attente', 'attribuee', 'annulee', 'expiree')),
    dateAttribution DATE NULL,
    dateExpiration DATE NULL
);

-- Create indexes
CREATE INDEX idx_livre_statut ON reservation (isbnLivre, statut);
CREATE INDEX idx_adherent_statut ON reservation (numeroAdherent, statut);
CREATE INDEX idx_date_reservation ON reservation (dateReservation);

-- Add foreign keys after table creation
ALTER TABLE reservation 
ADD CONSTRAINT fk_reservation_livre 
FOREIGN KEY (isbnLivre) REFERENCES livres(ISBN) ON DELETE CASCADE;

ALTER TABLE reservation 
ADD CONSTRAINT fk_reservation_adherent 
FOREIGN KEY (numeroAdherent) REFERENCES adherent(numero) ON DELETE CASCADE;

SELECT 'Reservation table created successfully!' AS message;
